version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - banking-spring-data:/var/lib/postgresql/data
volumes:
  banking-spring-data:
